[package]
name = "hyperbase"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
cxx-qt = "0.7"
cxx-qt-lib = { version = "0.7.0", features = ["full"] }

[build-dependencies]
cxx-build = "1.0"
cxx-qt-build = "0.7"
